# Default values for aws-resources-viewer
replicaCount: 1

# Docker image settings
# Update the tag as needed; Jenkins will handle updates
# For more information, see the Jenkins pipeline configuration.
image:
  repository: formy5000/resources_viewer
  pullPolicy: IfNotPresent
  tag: "sha-c4eb971"

nameOverride: ""
fullnameOverride: ""

# Service configuration
# The application listens on port 5001 by default
service:
  type: NodePort
  port: 5001
  targetPort: 5001
  nodePort: 30080

# Resource requests and limits
# Adjust these values based on your cluster's capacity and application needs
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Environment variables - AWS credentials loaded from Secret via envFrom
# The Secret 'aws-credentials' is created by Terraform during EC2 provisioning
env: []

# HPA (Horizontal Pod Autoscaler) Configuration
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
