apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aws-resources-viewer.fullname" . }}
  labels:
    {{- include "aws-resources-viewer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aws-resources-viewer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aws-resources-viewer.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "aws-resources-viewer.fullname" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        envFrom:
        - secretRef:
            name: aws-credentials
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if .Values.env }}
        {{- toYaml .Values.env | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
